### PR TITLE
Print all the things!

### PR DESCRIPTION
**Pull request by mikkelhegn**
Adding a flag to output component overview as well as information for all components. Is a nice way to generate documentation for your spin app.

### CODE REVIEW

**Comment by mikkelhegn** [comment]
@asteurer

**Comment by asteurer** [comment]
@mikkelhegn Just a heads up, I'm taking a break from writing code for a couple of weeks. I'll look this over the week after next

**Review by asteurer — APPROVED** [review]
LGTM

**Comment by mikkelhegn** [comment]
Thanks! I don't have merge rights, can you merge?

**Pull request merged**
